package internal

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// ACISubnetVars is written to subnets/<name>.yaml in the ACI IAC repo.
// The Terraform in that repo reads all files in subnets/ via fileset + yamldecode.
type ACISubnetVars struct {
	SubnetName   string `yaml:"subnet_name"`
	CIDR         string `yaml:"cidr"`
	Gateway      string `yaml:"gateway"`
	PrefixLength int    `yaml:"prefix_length"`
	VLANID       int    `yaml:"vlan_id"`
	Tenant       string `yaml:"tenant"`
	VRF          string `yaml:"vrf"`
	AP           string `yaml:"ap"`
	Domain       string `yaml:"domain"`
	Description  string `yaml:"description"`
}

// BlueCatSubnetVars is written to subnets/<name>.yaml in the BlueCat IAC repo.
type BlueCatSubnetVars struct {
	SubnetName    string `yaml:"subnet_name"`
	CIDR          string `yaml:"cidr"`
	Gateway       string `yaml:"gateway"`
	Description   string `yaml:"description"`
	Configuration string `yaml:"configuration"`
	View          string `yaml:"view"`
	ParentBlock   string `yaml:"parent_block"`
	DNSEnabled    bool   `yaml:"dns_enabled"`
}

// F5SubnetVars is written to <device>/subnets/<name>.yaml in the F5 IAC repo.
type F5SubnetVars struct {
	SubnetName              string       `yaml:"subnet_name"`
	CIDR                    string       `yaml:"cidr"`
	Gateway                 string       `yaml:"gateway"`
	PrefixLength            int          `yaml:"prefix_length"`
	VLANID                  int          `yaml:"vlan_id"`
	DeviceSelfIP            string       `yaml:"device_selfip"`
	FloatingSelfIP          string       `yaml:"floating_selfip,omitempty"`
	IsPrimary               bool         `yaml:"is_primary"`
	SubnetForwardingEnabled bool         `yaml:"subnet_forwarding_enabled"`
	LBEnabled               bool         `yaml:"lb_enabled"`
	LBVirtualServerIP       string       `yaml:"lb_virtual_server_ip,omitempty"`
	LBVirtualServerPort     int          `yaml:"lb_virtual_server_port,omitempty"`
	LBProtocol              string       `yaml:"lb_protocol,omitempty"`
	LBPoolMembers           []PoolMember `yaml:"lb_pool_members,omitempty"`
}

func marshalWithHeader(ticket string, extras []string, v any) (string, error) {
	data, err := yaml.Marshal(v)
	if err != nil {
		return "", err
	}
	lines := []string{
		"# Generated by self-service orchestrator — do not edit manually.",
		"# Request: " + ticket,
	}
	lines = append(lines, extras...)
	return strings.Join(lines, "\n") + "\n" + string(data), nil
}

// BuildACIVars returns the target file path and YAML content for the ACI IAC repo.
func BuildACIVars(req *Request, env *Environment, vlanID, prefixLen int) (path, content string, err error) {
	v := ACISubnetVars{
		SubnetName:   req.Subnet.Name,
		CIDR:         req.Subnet.CIDR,
		Gateway:      req.Subnet.Gateway,
		PrefixLength: prefixLen,
		VLANID:       vlanID,
		Tenant:       env.ACI.Tenant,
		VRF:          env.ACI.VRF,
		AP:           env.ACI.AP,
		Domain:       env.ACI.Domain,
		Description:  fmt.Sprintf("%s — %s", req.Metadata.Ticket, req.Metadata.Requester),
	}
	body, err := marshalWithHeader(req.Metadata.Ticket, nil, v)
	if err != nil {
		return "", "", err
	}
	return "subnets/" + req.Subnet.Name + ".yaml", body, nil
}

// BuildBlueCatVars returns the target file path and YAML content for the BlueCat IAC repo.
func BuildBlueCatVars(req *Request, env *Environment) (path, content string, err error) {
	v := BlueCatSubnetVars{
		SubnetName:    req.Subnet.Name,
		CIDR:          req.Subnet.CIDR,
		Gateway:       req.Subnet.Gateway,
		Description:   fmt.Sprintf("%s — %s", req.Metadata.Ticket, req.Metadata.Requester),
		Configuration: env.BlueCat.Configuration,
		View:          env.BlueCat.View,
		ParentBlock:   env.BlueCat.ParentBlock,
		DNSEnabled:    req.Features.DNSEnabled(),
	}
	body, err := marshalWithHeader(req.Metadata.Ticket, nil, v)
	if err != nil {
		return "", "", err
	}
	return "subnets/" + req.Subnet.Name + ".yaml", body, nil
}

// BuildF5Vars returns the target file path and YAML content for one F5 device.
// All device files are committed to the F5 IAC repo in a single PR.
func BuildF5Vars(req *Request, device *F5Device, vlanID, prefixLen int, deviceSelfIP, floatingSelfIP string) (path, content string, err error) {
	isPrimary := strings.HasSuffix(device.Folder, "-primary")
	lb := req.Features.LoadBalancing

	v := F5SubnetVars{
		SubnetName:              req.Subnet.Name,
		CIDR:                    req.Subnet.CIDR,
		Gateway:                 req.Subnet.Gateway,
		PrefixLength:            prefixLen,
		VLANID:                  vlanID,
		DeviceSelfIP:            deviceSelfIP,
		IsPrimary:               isPrimary,
		SubnetForwardingEnabled: req.Features.SubnetFwdEnabled(),
		LBEnabled:               lb.Enabled,
	}
	if isPrimary {
		v.FloatingSelfIP = floatingSelfIP
	}
	if lb.Enabled {
		v.LBVirtualServerIP = lb.VirtualServerIP
		v.LBVirtualServerPort = lb.VirtualServerPort
		v.LBProtocol = lb.Protocol
		if v.LBProtocol == "" {
			v.LBProtocol = "tcp"
		}
		v.LBPoolMembers = lb.PoolMembers
	}

	body, err := marshalWithHeader(req.Metadata.Ticket, []string{"# Device: " + device.Folder}, v)
	if err != nil {
		return "", "", err
	}
	return device.Folder + "/subnets/" + req.Subnet.Name + ".yaml", body, nil
}
