package internal

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

type ACISubnetVars struct {
	SubnetName   string `yaml:"subnet_name"`
	Environment  string `yaml:"environment"`
	CIDR         string `yaml:"cidr"`
	Gateway      string `yaml:"gateway"`
	PrefixLength int    `yaml:"prefix_length"`
	VLANID       int    `yaml:"vlan_id"`
	Tenant       string `yaml:"tenant"`
	VRF          string `yaml:"vrf"`
	AP           string `yaml:"ap"`
	Domain       string `yaml:"domain"`
	Description  string `yaml:"description"`
}

type BlueCatSubnetVars struct {
	SubnetName    string `yaml:"subnet_name"`
	Environment   string `yaml:"environment"`
	CIDR          string `yaml:"cidr"`
	Gateway       string `yaml:"gateway"`
	Description   string `yaml:"description"`
	Configuration string `yaml:"configuration"`
	View          string `yaml:"view"`
	ParentBlock   string `yaml:"parent_block"`
	DNSEnabled    bool   `yaml:"dns_enabled"`
}

// F5SubnetVars is written to <device>/subnets/<name>.yaml in the F5 IAC repo.
// Subnet forwarding (AS3 route advertisement) is always enabled for loadbalancer devices.
// VirtualServers is non-empty only when LB virtual servers are requested.
type F5SubnetVars struct {
	SubnetName     string          `yaml:"subnet_name"`
	Environment    string          `yaml:"environment"`
	CIDR           string          `yaml:"cidr"`
	Gateway        string          `yaml:"gateway"`
	PrefixLength   int             `yaml:"prefix_length"`
	VLANID         int             `yaml:"vlan_id"`
	DeviceSelfIP   string          `yaml:"device_selfip"`
	FloatingSelfIP string          `yaml:"floating_selfip,omitempty"`
	IsPrimary      bool            `yaml:"is_primary"`
	VirtualServers []VirtualServer `yaml:"virtual_servers,omitempty"`
}

func marshalWithHeader(ticket string, extras []string, v any) (string, error) {
	data, err := yaml.Marshal(v)
	if err != nil {
		return "", err
	}
	lines := []string{
		"# Generated by self-service orchestrator — do not edit manually.",
		"# Request: " + ticket,
	}
	lines = append(lines, extras...)
	return strings.Join(lines, "\n") + "\n" + string(data), nil
}

func BuildACIVars(req *Request, env *Environment, vlanID, prefixLen int) (path, content string, err error) {
	v := ACISubnetVars{
		SubnetName:   req.Subnet.Name,
		Environment:  req.Subnet.Environment,
		CIDR:         req.Subnet.CIDR,
		Gateway:      req.Subnet.Gateway,
		PrefixLength: prefixLen,
		VLANID:       vlanID,
		Tenant:       env.ACI.Tenant,
		VRF:          env.ACI.VRF,
		AP:           env.ACI.AP,
		Domain:       env.ACI.Domain,
		Description:  fmt.Sprintf("%s — %s", req.Metadata.Ticket, req.Metadata.Requester),
	}
	body, err := marshalWithHeader(req.Metadata.Ticket, nil, v)
	if err != nil {
		return "", "", err
	}
	return "subnets/" + req.Subnet.Name + ".yaml", body, nil
}

func BuildBlueCatVars(req *Request, env *Environment) (path, content string, err error) {
	v := BlueCatSubnetVars{
		SubnetName:    req.Subnet.Name,
		Environment:   req.Subnet.Environment,
		CIDR:          req.Subnet.CIDR,
		Gateway:       req.Subnet.Gateway,
		Description:   fmt.Sprintf("%s — %s", req.Metadata.Ticket, req.Metadata.Requester),
		Configuration: env.BlueCat.Configuration,
		View:          env.BlueCat.View,
		ParentBlock:   env.BlueCat.ParentBlock,
		DNSEnabled:    req.Features.DNSEnabled(),
	}
	body, err := marshalWithHeader(req.Metadata.Ticket, nil, v)
	if err != nil {
		return "", "", err
	}
	return "subnets/" + req.Subnet.Name + ".yaml", body, nil
}

func BuildF5Vars(req *Request, device *F5Device, vlanID, prefixLen int, deviceSelfIP, floatingSelfIP string) (path, content string, err error) {
	isPrimary := strings.HasSuffix(device.Folder, "-primary")

	// Normalize protocol default on each virtual server
	vses := make([]VirtualServer, len(req.Features.VirtualServers))
	for i, vs := range req.Features.VirtualServers {
		vses[i] = vs
		if vses[i].Protocol == "" {
			vses[i].Protocol = "tcp"
		}
	}

	v := F5SubnetVars{
		SubnetName:     req.Subnet.Name,
		Environment:    req.Subnet.Environment,
		CIDR:           req.Subnet.CIDR,
		Gateway:        req.Subnet.Gateway,
		PrefixLength:   prefixLen,
		VLANID:         vlanID,
		DeviceSelfIP:   deviceSelfIP,
		IsPrimary:      isPrimary,
		VirtualServers: vses,
	}
	if isPrimary {
		v.FloatingSelfIP = floatingSelfIP
	}

	body, err := marshalWithHeader(req.Metadata.Ticket, []string{"# Device: " + device.Folder}, v)
	if err != nil {
		return "", "", err
	}
	return device.Folder + "/subnets/" + req.Subnet.Name + ".yaml", body, nil
}
